-- =====================================================================
-- V10 - Agenda de citas
--
-- Planificar la entrada de motos antes de que lleguen. Hasta ahora la orden
-- de trabajo nacia cuando la moto ya estaba en el elevador, asi que no habia
-- forma de ver cuanto trabajo entra manana ni de decirle a un cliente «el
-- jueves lo tengo lleno, mejor el viernes».
--
-- Una cita NO es una orden de trabajo: es un compromiso de que una moto
-- entrara. Cuando llega de verdad, la cita se convierte en OT y ambas quedan
-- enlazadas. Se guardan aparte a proposito: las citas se cancelan y se mueven
-- de dia con normalidad, y una OT que se pudiera mover de fecha o desaparecer
-- destrozaria la numeracion correlativa y el historial.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Capacidad del taller
-- ---------------------------------------------------------------------
-- Horas de trabajo que caben en un dia. Es lo que permite avisar de que un
-- dia esta lleno, en vez de dejar apuntar doce motos para el mismo martes.
ALTER TABLE configuracion_taller
    ADD COLUMN capacidad_diaria_horas NUMERIC(5,2) NOT NULL DEFAULT 16.00;

ALTER TABLE configuracion_taller
    ADD CONSTRAINT ck_configuracion_capacidad CHECK (capacidad_diaria_horas > 0);

COMMENT ON COLUMN configuracion_taller.capacidad_diaria_horas IS
    'Horas de taller disponibles al dia. Sirve para avisar de dias saturados en la agenda.';


-- ---------------------------------------------------------------------
-- Citas
-- ---------------------------------------------------------------------
CREATE TABLE cita (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fecha_hora          TIMESTAMPTZ  NOT NULL,
    -- Lo que se espera tener la moto ocupando un puesto. Es una estimacion de
    -- mostrador, no un compromiso: sirve para repartir la carga del dia.
    duracion_estimada   NUMERIC(5,2) NOT NULL DEFAULT 1.00,

    -- La moto puede no estar dada de alta todavia: la mitad de las citas se
    -- cogen por telefono de gente que llama por primera vez. Si la hay, se
    -- enlaza y manda ella; si no, se apunta a mano lo justo para reconocerla
    -- cuando entre por la puerta.
    moto_id             BIGINT,
    contacto_nombre     VARCHAR(150),
    contacto_telefono   VARCHAR(30),
    descripcion_moto    VARCHAR(150),

    motivo              TEXT         NOT NULL,
    tecnico_id          BIGINT,
    estado              VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    observaciones       TEXT,

    -- Se rellena cuando la moto entra de verdad y la cita se convierte en OT.
    orden_trabajo_id    BIGINT,
    motivo_cancelacion  VARCHAR(300),

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by          BIGINT,
    version             INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_cita_estado CHECK (estado IN (
        'PENDIENTE', 'CONFIRMADA', 'ATENDIDA', 'CANCELADA', 'NO_PRESENTADO')),
    CONSTRAINT ck_cita_duracion CHECK (duracion_estimada > 0 AND duracion_estimada <= 24),

    -- O la moto esta en el sistema, o hay con quien contactar. Una cita sin
    -- ninguna de las dos cosas es un hueco ocupado que nadie sabe de quien es.
    CONSTRAINT ck_cita_identificacion CHECK (
        moto_id IS NOT NULL OR (contacto_nombre IS NOT NULL AND contacto_telefono IS NOT NULL)),

    -- Una cita atendida es la que ya tiene su OT abierta, y solo esa.
    CONSTRAINT ck_cita_atendida CHECK (
        (estado = 'ATENDIDA') = (orden_trabajo_id IS NOT NULL)),

    CONSTRAINT ck_cita_cancelacion CHECK (
        motivo_cancelacion IS NULL OR estado IN ('CANCELADA', 'NO_PRESENTADO')),

    CONSTRAINT fk_cita_moto       FOREIGN KEY (moto_id)          REFERENCES moto (id),
    CONSTRAINT fk_cita_tecnico    FOREIGN KEY (tecnico_id)       REFERENCES usuario (id),
    CONSTRAINT fk_cita_orden      FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo (id),
    CONSTRAINT fk_cita_created_by FOREIGN KEY (created_by)       REFERENCES usuario (id),
    CONSTRAINT fk_cita_updated_by FOREIGN KEY (updated_by)       REFERENCES usuario (id)
);

-- La consulta de la agenda es siempre «que hay entre estos dos dias», asi que
-- el indice va por fecha. El parcial deja fuera lo que ya no ocupa hueco.
CREATE INDEX ix_cita_fecha ON cita (fecha_hora);
CREATE INDEX ix_cita_fecha_viva ON cita (fecha_hora)
    WHERE estado IN ('PENDIENTE', 'CONFIRMADA');
CREATE INDEX ix_cita_moto ON cita (moto_id, fecha_hora DESC) WHERE moto_id IS NOT NULL;
CREATE INDEX ix_cita_tecnico ON cita (tecnico_id, fecha_hora) WHERE tecnico_id IS NOT NULL;

-- Una OT nace de una cita como mucho, no de dos.
CREATE UNIQUE INDEX ux_cita_orden ON cita (orden_trabajo_id) WHERE orden_trabajo_id IS NOT NULL;

-- Mismo trigger de auditoria que el resto de tablas (V6): refresca updated_at
-- aunque el UPDATE no venga de la aplicacion.
CREATE TRIGGER tg_cita_updated_at
    BEFORE UPDATE ON cita
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

COMMENT ON TABLE  cita                    IS 'Cita de entrada al taller. Se convierte en orden de trabajo cuando la moto llega.';
COMMENT ON COLUMN cita.duracion_estimada  IS 'Horas que se espera que la moto ocupe puesto. Alimenta la carga del dia.';
COMMENT ON COLUMN cita.moto_id            IS 'Moto del sistema. Nula cuando la cita es de alguien que aun no esta dado de alta.';
COMMENT ON COLUMN cita.orden_trabajo_id   IS 'OT que nacio de esta cita. Solo se rellena al atenderla.';
