-- =====================================================================
-- Servicios tipo (plantillas de orden de trabajo)
--
-- Una «revisión de 10.000 km» son siempre las mismas horas y el mismo kit
-- de piezas. Hasta ahora había que teclear esas seis o siete líneas una a
-- una en cada OT, con el riesgo de que a la tercera del día se olvide el
-- filtro de aire y salga una factura corta.
--
-- Una plantilla es solo eso: una lista de líneas guardada con un nombre. NO
-- lleva precios. Los precios se leen del catálogo y de la tarifa de la OT en
-- el momento de volcarla, igual que si se hubieran tecleado a mano, y se
-- congelan allí. Guardarlos aquí sería crear un segundo catálogo que se
-- queda viejo sin que nadie se entere.
--
-- Volcar una plantilla no crea ningún vínculo: a partir de ese momento las
-- líneas son de la OT y se editan, se borran o se cambian de cantidad como
-- cualquier otra. La plantilla es un atajo de tecleo, no una suscripción.
-- =====================================================================

CREATE TABLE servicio_tipo (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(120)  NOT NULL,
    descripcion  VARCHAR(400),
    -- Horas y piezas orientativas se ven en la lista sin abrir la plantilla,
    -- pero se calculan al vuelo desde las lineas: no se guardan aqui para que
    -- no puedan contradecirlas.
    activo       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by   BIGINT,
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by   BIGINT,
    version      INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT ck_servicio_tipo_nombre CHECK (LENGTH(TRIM(nombre)) > 0)
);

COMMENT ON TABLE  servicio_tipo             IS 'Plantilla de orden de trabajo: nombre y lista de lineas, sin precios.';
COMMENT ON COLUMN servicio_tipo.nombre      IS 'Como lo llama el taller: «Revision 10.000 km», «Cambio de aceite y filtro».';
COMMENT ON COLUMN servicio_tipo.descripcion IS 'Que incluye el servicio. Sirve de recordatorio al elegirlo en la OT.';
COMMENT ON COLUMN servicio_tipo.activo      IS 'Las plantillas no se borran: se desactivan, para no perder las que ya se usaron.';

-- Dos plantillas con el mismo nombre solo generan dudas al elegir en la OT.
-- Se comparan en minusculas; los acentos no se normalizan porque unaccent no
-- esta instalado y no compensa una extension por esto.
CREATE UNIQUE INDEX ux_servicio_tipo_nombre ON servicio_tipo (LOWER(TRIM(nombre)));

-- El desplegable de la OT solo ofrece las activas.
CREATE INDEX ix_servicio_tipo_activo ON servicio_tipo (activo) WHERE activo;


CREATE TABLE linea_servicio_tipo (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio_tipo_id  BIGINT        NOT NULL REFERENCES servicio_tipo (id) ON DELETE CASCADE,
    numero_linea      INTEGER       NOT NULL,
    tipo              VARCHAR(20)   NOT NULL,
    descripcion       VARCHAR(300),
    pieza_id          BIGINT        REFERENCES pieza (id),
    cantidad          NUMERIC(12,3) NOT NULL,

    CONSTRAINT ck_linea_servicio_tipo_tipo
        CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA')),

    -- Cada tipo de linea necesita cosas distintas y no admite las del otro: la
    -- mano de obra se describe con texto y no apunta a ninguna pieza; la pieza
    -- viene del catalogo y de alli toma su descripcion.
    CONSTRAINT ck_linea_servicio_tipo_coherente CHECK (
        (tipo = 'MANO_DE_OBRA' AND pieza_id IS NULL     AND descripcion IS NOT NULL)
     OR (tipo = 'PIEZA'        AND pieza_id IS NOT NULL)
    ),

    CONSTRAINT ck_linea_servicio_tipo_cantidad CHECK (cantidad > 0),

    CONSTRAINT uq_linea_servicio_tipo_orden UNIQUE (servicio_tipo_id, numero_linea)
);

COMMENT ON TABLE  linea_servicio_tipo             IS 'Linea de una plantilla. Sin precio: se lee del catalogo al volcarla en la OT.';
COMMENT ON COLUMN linea_servicio_tipo.tipo        IS 'MANO_DE_OBRA (cantidad = horas) o PIEZA (cantidad = unidades).';
COMMENT ON COLUMN linea_servicio_tipo.descripcion IS 'Obligatoria en mano de obra. En piezas manda la descripcion del catalogo.';
COMMENT ON COLUMN linea_servicio_tipo.cantidad    IS 'Horas o unidades previstas. En la OT se puede ajustar despues.';

CREATE INDEX ix_linea_servicio_tipo_servicio ON linea_servicio_tipo (servicio_tipo_id);

-- Para saber que plantillas quedan tocadas si se da de baja una pieza.
CREATE INDEX ix_linea_servicio_tipo_pieza ON linea_servicio_tipo (pieza_id) WHERE pieza_id IS NOT NULL;


-- ---------------------------------------------------------------------
-- Blindaje de acceso.
--
-- V8 dejo revocados los permisos por defecto para `anon` y `authenticated`,
-- asi que estas tablas nacen sin GRANT. Lo que V8 NO puede hacer por
-- adelantado es activar RLS en tablas que aun no existian, y eso hay que
-- repetirlo aqui: sin ello, una tabla nueva seria la unica sin la segunda
-- barrera. Mismo criterio que alli: solo si el entorno es Supabase, porque
-- en PostgreSQL estandar esos roles no existen.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        ALTER TABLE public.servicio_tipo       ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.servicio_tipo       FORCE  ROW LEVEL SECURITY;
        ALTER TABLE public.linea_servicio_tipo ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.linea_servicio_tipo FORCE  ROW LEVEL SECURITY;
        RAISE NOTICE 'Blindaje aplicado a servicio_tipo y linea_servicio_tipo.';
    ELSE
        RAISE NOTICE 'Roles de Supabase no encontrados: se omite el blindaje.';
    END IF;
END;
$$;
