-- =====================================================================
-- V14 - Roles con permisos a la carta
-- =====================================================================
--
-- Hasta aqui los roles eran tres y estaban clavados en el codigo: ADMIN,
-- MOSTRADOR y TECNICO. Servia mientras el reparto de tareas fuera ese, pero en
-- cuanto un taller quiere «que Juan pueda dar de alta clientes pero no tocar el
-- almacen» no hay donde tocar.
--
-- Ahora el rol es una fila con su lista de permisos, y el administrador los
-- compone. El catalogo de permisos SI sigue en el codigo (enum Permiso): un
-- permiso que no se comprueba en ninguna parte seria una casilla que no protege
-- nada.
--
-- Los tres roles de siempre se crean aqui con exactamente los permisos que
-- tenian, de modo que despues de esta migracion nadie gana ni pierde nada.

-- ---------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------
CREATE TABLE rol (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL,
    descripcion VARCHAR(200),
    -- Un rol de sistema no se puede borrar. ADMIN ademas no se puede editar:
    -- es el que reparte los permisos, y dejar que se quite el suyo propio es
    -- la forma mas rapida de quedarse fuera del programa para siempre.
    sistema     BOOLEAN      NOT NULL DEFAULT FALSE,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    version     INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_rol_nombre CHECK (length(trim(nombre)) > 0)
);

CREATE UNIQUE INDEX uq_rol_nombre_unico ON rol (upper(nombre));

COMMENT ON TABLE  rol         IS 'Roles del taller. Los compone el administrador a partir del catalogo de permisos.';
COMMENT ON COLUMN rol.sistema IS 'Rol de serie: no se borra. El de administrador tampoco se edita.';


-- ---------------------------------------------------------------------
-- Permisos de cada rol
-- ---------------------------------------------------------------------
CREATE TABLE rol_permiso (
    rol_id  BIGINT      NOT NULL,
    permiso VARCHAR(50) NOT NULL,

    CONSTRAINT pk_rol_permiso  PRIMARY KEY (rol_id, permiso),
    CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (rol_id) REFERENCES rol (id) ON DELETE CASCADE
);

COMMENT ON TABLE rol_permiso IS 'Permisos concedidos a un rol. El catalogo valido vive en el enum Permiso.';


-- ---------------------------------------------------------------------
-- Los tres roles de siempre, con lo que ya podian hacer
-- ---------------------------------------------------------------------
INSERT INTO rol (id, nombre, descripcion, sistema) VALUES
    (1, 'Administracion', 'Acceso completo, incluidos los ajustes fiscales, los precios y el reparto de permisos.', TRUE),
    (2, 'Mostrador',      'Clientes, motos, ordenes de trabajo y facturacion. El almacen solo lo consulta.', TRUE),
    (3, 'Taller',         'Las ordenes que tiene asignadas. No ve importes ni precios.', TRUE);

-- Administracion: todo el catalogo. Se listan uno a uno y no con un comodin
-- porque no hay comodin que valga: si manana se anade un permiso, el enum lo
-- concede al rol de sistema desde el codigo (ver RolService).
INSERT INTO rol_permiso (rol_id, permiso)
SELECT 1, p FROM (VALUES
    ('CLIENTES_VER'), ('CLIENTES_CREAR'), ('CLIENTES_EDITAR'), ('CLIENTES_DATOS_FISCALES'), ('CLIENTES_BAJA'),
    ('MOTOS_VER'), ('MOTOS_CREAR'), ('MOTOS_EDITAR'), ('MOTOS_CAMBIAR_PROPIETARIO'), ('MOTOS_BAJA'),
    ('ORDENES_VER'), ('ORDENES_VER_TODAS'), ('ORDENES_ABRIR'), ('ORDENES_DIAGNOSTICAR'),
    ('ORDENES_LINEAS_MANO_OBRA'), ('ORDENES_LINEAS_MATERIAL'), ('ORDENES_LINEAS_QUITAR'),
    ('ORDENES_ESTADO'), ('ORDENES_ASIGNAR_TECNICO'), ('ORDENES_PREPARAR'), ('ORDENES_APROBAR'), ('ORDENES_ENTREGAR'),
    ('IMPORTES_VER'), ('PRECIOS_EDITAR'), ('DESCUENTOS_APLICAR'),
    ('FACTURAS_VER'), ('FACTURAS_EMITIR'), ('FACTURAS_RECTIFICAR'), ('FACTURAS_SERIES'),
    ('FACTURACION_EXPORTAR'), ('INFORMES_VER'),
    ('ALMACEN_VER'), ('PIEZAS_CREAR'), ('PIEZAS_EDITAR'), ('PIEZAS_PRECIOS'), ('ALMACEN_MOVER'), ('PROVEEDORES_GESTIONAR'),
    ('AGENDA_VER'), ('AGENDA_GESTIONAR'), ('SERVICIOS_VER'), ('SERVICIOS_GESTIONAR'),
    ('AJUSTES_VER'), ('AJUSTES_EDITAR'), ('USUARIOS_GESTIONAR'), ('ROLES_GESTIONAR')
) AS catalogo(p);

-- Mostrador: lo que hacia. Sin preparar ordenes (era solo de direccion), sin
-- series de facturacion, y del almacen solo la consulta y los proveedores.
INSERT INTO rol_permiso (rol_id, permiso)
SELECT 2, p FROM (VALUES
    ('CLIENTES_VER'), ('CLIENTES_CREAR'), ('CLIENTES_EDITAR'), ('CLIENTES_DATOS_FISCALES'), ('CLIENTES_BAJA'),
    ('MOTOS_VER'), ('MOTOS_CREAR'), ('MOTOS_EDITAR'), ('MOTOS_CAMBIAR_PROPIETARIO'), ('MOTOS_BAJA'),
    ('ORDENES_VER'), ('ORDENES_VER_TODAS'), ('ORDENES_ABRIR'), ('ORDENES_DIAGNOSTICAR'),
    ('ORDENES_LINEAS_MANO_OBRA'), ('ORDENES_LINEAS_MATERIAL'), ('ORDENES_LINEAS_QUITAR'),
    ('ORDENES_ESTADO'), ('ORDENES_ASIGNAR_TECNICO'), ('ORDENES_APROBAR'), ('ORDENES_ENTREGAR'),
    ('IMPORTES_VER'), ('PRECIOS_EDITAR'), ('DESCUENTOS_APLICAR'),
    ('FACTURAS_VER'), ('FACTURAS_EMITIR'), ('FACTURAS_RECTIFICAR'), ('FACTURACION_EXPORTAR'), ('INFORMES_VER'),
    ('ALMACEN_VER'), ('PROVEEDORES_GESTIONAR'),
    ('AGENDA_VER'), ('AGENDA_GESTIONAR'), ('SERVICIOS_VER'),
    ('AJUSTES_VER')
) AS catalogo(p);

-- Taller: sus ordenes y poco mas. Sin IMPORTES_VER, que es lo que le vacia los
-- precios en las respuestas, y sin ORDENES_VER_TODAS, que es lo que le limita
-- el tablero a las suyas.
INSERT INTO rol_permiso (rol_id, permiso)
SELECT 3, p FROM (VALUES
    ('CLIENTES_VER'),
    ('MOTOS_VER'),
    ('ORDENES_VER'), ('ORDENES_DIAGNOSTICAR'),
    ('ORDENES_LINEAS_MANO_OBRA'), ('ORDENES_LINEAS_MATERIAL'), ('ORDENES_LINEAS_QUITAR'),
    ('ORDENES_ESTADO'), ('ORDENES_ASIGNAR_TECNICO'),
    ('ALMACEN_VER'),
    ('AGENDA_VER'), ('SERVICIOS_VER')
) AS catalogo(p);

-- La secuencia del id tiene que continuar despues de los tres fijos.
SELECT setval(pg_get_serial_sequence('rol', 'id'), 3);


-- ---------------------------------------------------------------------
-- El usuario pasa a apuntar a su rol
-- ---------------------------------------------------------------------
ALTER TABLE usuario ADD COLUMN rol_id BIGINT;

UPDATE usuario SET rol_id = CASE rol
    WHEN 'ADMIN'     THEN 1
    WHEN 'MOSTRADOR' THEN 2
    WHEN 'TECNICO'   THEN 3
END;

ALTER TABLE usuario ALTER COLUMN rol_id SET NOT NULL;
ALTER TABLE usuario ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol (id);

-- El enum de texto ya no manda: se va, con su check y su indice.
DROP INDEX IF EXISTS ix_usuario_rol;
ALTER TABLE usuario DROP CONSTRAINT IF EXISTS ck_usuario_rol;
ALTER TABLE usuario DROP COLUMN rol;

CREATE INDEX ix_usuario_rol ON usuario (rol_id) WHERE activo;

COMMENT ON COLUMN usuario.rol_id IS 'Rol del usuario. Los permisos salen de rol_permiso.';
