-- =====================================================================
-- Registro de jornada (fichaje)
-- =====================================================================
--
-- En Espana el registro de jornada es obligatorio (art. 34.9 del Estatuto
-- de los Trabajadores). Eso no es un detalle: marca como tiene que estar
-- hecha esta tabla.
--
--   * Se guarda el inicio y el fin de cada jornada, no un total. El total
--     se calcula; lo que hay que poder ensenar a una inspeccion son las
--     horas concretas.
--   * Se conserva cuatro anos. Nada de borrar fichajes viejos.
--   * Una correccion no pisa el original: se guarda lo que se fichó y,
--     aparte, lo que corrigio el administrador, quien lo hizo y por que.
--     Un registro que se puede reescribir sin rastro no prueba nada.
--
-- La restriccion importante es la ultima: un usuario no puede tener dos
-- jornadas abiertas a la vez. Se hace con indice unico parcial y no
-- comprobandolo en el servicio, porque dos pulsaciones seguidas del boton
-- —o dos pestanas— colarian la segunda entre la lectura y la escritura.
-- =====================================================================

CREATE TABLE fichaje (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT       NOT NULL,

    -- Lo que quedo registrado al pulsar los botones. No se toca nunca.
    inicio              TIMESTAMPTZ  NOT NULL,
    fin                 TIMESTAMPTZ,

    -- La correccion del administrador, si la hubo. Nulas mientras nadie
    -- corrija: entonces valen las de arriba.
    inicio_corregido    TIMESTAMPTZ,
    fin_corregido       TIMESTAMPTZ,
    motivo_correccion   VARCHAR(300),
    corregido_por       BIGINT,
    corregido_en        TIMESTAMPTZ,

    -- Cerrada por el administrador porque el trabajador se fue sin fichar
    -- la salida. Se marca para que no cuente como una jornada normal.
    cerrada_por_olvido  BOOLEAN      NOT NULL DEFAULT FALSE,

    observaciones       TEXT,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by          BIGINT,
    version             INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT fk_fichaje_usuario   FOREIGN KEY (usuario_id)    REFERENCES usuario (id),
    CONSTRAINT fk_fichaje_corrector FOREIGN KEY (corregido_por) REFERENCES usuario (id),

    -- Una jornada no puede acabar antes de empezar.
    CONSTRAINT ck_fichaje_orden CHECK (fin IS NULL OR fin >= inicio),
    CONSTRAINT ck_fichaje_orden_corregido
        CHECK (fin_corregido IS NULL OR inicio_corregido IS NULL OR fin_corregido >= inicio_corregido),
    -- Corregir exige decir por que y quien: si no, no es una correccion,
    -- es un cambio sin firmar.
    CONSTRAINT ck_fichaje_correccion_firmada CHECK (
        (inicio_corregido IS NULL AND fin_corregido IS NULL)
        OR (motivo_correccion IS NOT NULL AND corregido_por IS NOT NULL)
    )
);

-- Una sola jornada abierta por persona. Parcial a proposito: las cerradas
-- pueden ser tantas como dias tenga el ano.
CREATE UNIQUE INDEX uq_fichaje_abierto_por_usuario
    ON fichaje (usuario_id)
    WHERE fin IS NULL;

-- El listado del administrador siempre filtra por fecha, y el del propio
-- trabajador por el suyo.
CREATE INDEX ix_fichaje_usuario_inicio ON fichaje (usuario_id, inicio DESC);
CREATE INDEX ix_fichaje_inicio         ON fichaje (inicio DESC);

COMMENT ON TABLE  fichaje IS 'Registro de jornada. Obligatorio por el art. 34.9 ET; se conserva 4 anos.';
COMMENT ON COLUMN fichaje.inicio_corregido IS 'Correccion del administrador. El fichaje original nunca se sobrescribe.';
COMMENT ON INDEX  uq_fichaje_abierto_por_usuario IS 'Cierra la carrera del doble clic en «empezar jornada».';
