-- =====================================================================
-- V1 - Usuarios del sistema, configuracion fiscal del taller y tipos de IVA
-- =====================================================================
-- Convenciones del esquema:
--   * Identificadores generados con IDENTITY "BY DEFAULT" para que los
--     scripts de datos demo puedan fijar ids explicitos.
--   * Importes siempre NUMERIC (nunca float/double).
--   * Fechas con huso horario (TIMESTAMPTZ). El taller opera en Europe/Madrid.
--   * Columnas de auditoria homogeneas: created_at/by, updated_at/by, version.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Usuarios
-- ---------------------------------------------------------------------
CREATE TABLE usuario (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    email           VARCHAR(150),
    telefono        VARCHAR(30),
    rol             VARCHAR(20)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_acceso   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    version         INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_rol      CHECK (rol IN ('ADMIN', 'MOSTRADOR', 'TECNICO')),
    CONSTRAINT fk_usuario_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_usuario_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

CREATE INDEX ix_usuario_rol    ON usuario (rol) WHERE activo;
CREATE INDEX ix_usuario_activo ON usuario (activo);

COMMENT ON TABLE  usuario               IS 'Usuarios que acceden al sistema. Baja logica mediante el flag activo.';
COMMENT ON COLUMN usuario.password_hash IS 'Hash BCrypt de la contrasena. Nunca se almacena la contrasena en claro.';
COMMENT ON COLUMN usuario.rol           IS 'ADMIN | MOSTRADOR | TECNICO';


-- ---------------------------------------------------------------------
-- Tipos de IVA aplicables
-- ---------------------------------------------------------------------
-- El porcentaje vigente vive aqui, pero cada linea de OT y de factura
-- guarda ademas una COPIA CONGELADA del porcentaje aplicado. Si Hacienda
-- cambia un tipo, los documentos ya emitidos no se alteran.
CREATE TABLE tipo_iva (
    codigo      VARCHAR(20)  PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL,
    porcentaje  NUMERIC(5,2) NOT NULL,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    version     INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_tipo_iva_porcentaje  CHECK (porcentaje >= 0 AND porcentaje <= 100),
    CONSTRAINT fk_tipo_iva_created_by  FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_tipo_iva_updated_by  FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

COMMENT ON TABLE tipo_iva IS 'Catalogo de tipos de IVA. El porcentaje se copia (se congela) en cada linea emitida.';

INSERT INTO tipo_iva (codigo, descripcion, porcentaje) VALUES
    ('GENERAL',       'IVA general (21%)',        21.00),
    ('REDUCIDO',      'IVA reducido (10%)',       10.00),
    ('SUPERREDUCIDO', 'IVA superreducido (4%)',    4.00),
    ('EXENTO',        'Operacion exenta de IVA',   0.00);


-- ---------------------------------------------------------------------
-- Configuracion fiscal y operativa del taller (fila unica)
-- ---------------------------------------------------------------------
CREATE TABLE configuracion_taller (
    id                    INTEGER      PRIMARY KEY DEFAULT 1,
    razon_social          VARCHAR(200) NOT NULL,
    nif                   VARCHAR(20)  NOT NULL,
    direccion             VARCHAR(200) NOT NULL,
    codigo_postal         VARCHAR(10)  NOT NULL,
    ciudad                VARCHAR(100) NOT NULL,
    provincia             VARCHAR(100) NOT NULL,
    pais                  VARCHAR(60)  NOT NULL DEFAULT 'Espana',
    telefono              VARCHAR(30),
    email                 VARCHAR(150),
    -- Tarifa por defecto de mano de obra. Se congela en cada OT al abrirla.
    tarifa_hora_defecto   NUMERIC(12,2) NOT NULL,
    tipo_iva_defecto      VARCHAR(20)   NOT NULL DEFAULT 'GENERAL',
    -- Datos del software de facturacion, exigidos en el registro de facturacion.
    software_nombre       VARCHAR(100)  NOT NULL DEFAULT 'MotorSport19 Taller',
    software_version      VARCHAR(30)   NOT NULL DEFAULT '0.1.0',
    software_nif          VARCHAR(20),
    -- URL base del servicio de verificacion que se codifica en el QR de la factura.
    url_verificacion_qr   VARCHAR(300),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by            BIGINT,
    version               INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT ck_configuracion_fila_unica CHECK (id = 1),
    CONSTRAINT ck_configuracion_tarifa     CHECK (tarifa_hora_defecto > 0),
    CONSTRAINT fk_configuracion_tipo_iva   FOREIGN KEY (tipo_iva_defecto) REFERENCES tipo_iva (codigo),
    CONSTRAINT fk_configuracion_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_configuracion_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

COMMENT ON TABLE  configuracion_taller    IS 'Datos fiscales del emisor. Tabla de una sola fila (id = 1), garantizado por CHECK.';
COMMENT ON COLUMN configuracion_taller.id IS 'Siempre 1: la restriccion ck_configuracion_fila_unica impide mas filas.';
