-- ============================================================
-- V20 - Historial de estados de la cita
-- ============================================================
-- La cita ya guardaba QUIEN la creo (created_by) y en que estado esta AHORA,
-- pero no lo de en medio: quien la confirmo, quien la movio de dia, quien
-- registro que el cliente no aparecio. Con solo updated_by, el ultimo que la
-- toca borra a todos los anteriores, y eso no es un historial.
--
-- Se copia el patron que ya usa la OT (cambio_estado_ot): una fila por
-- movimiento, append-only, con quien y por que.
-- ============================================================

CREATE TABLE cambio_estado_cita (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id         BIGINT      NOT NULL,
    estado_anterior VARCHAR(20),
    estado_nuevo    VARCHAR(20) NOT NULL,
    fecha           TIMESTAMPTZ NOT NULL DEFAULT now(),
    usuario_id      BIGINT,
    motivo          VARCHAR(300),

    CONSTRAINT fk_cambio_cita_cita    FOREIGN KEY (cita_id)    REFERENCES cita (id),
    CONSTRAINT fk_cambio_cita_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

-- El listado siempre se pide de una cita concreta y en orden.
CREATE INDEX ix_cambio_estado_cita_cita ON cambio_estado_cita (cita_id, fecha);

-- Y el rastro de la jornada lo pide por persona y tramo de tiempo.
CREATE INDEX ix_cambio_estado_cita_usuario ON cambio_estado_cita (usuario_id, fecha);

-- Append-only, igual que el historial de la OT: un error no se reescribe, se
-- corrige con el movimiento siguiente.
CREATE TRIGGER tg_cambio_estado_cita_inmutable
    BEFORE UPDATE OR DELETE ON cambio_estado_cita
    FOR EACH ROW EXECUTE FUNCTION fn_bloquear_modificacion();

COMMENT ON TABLE cambio_estado_cita IS
    'Historial append-only de la agenda: quien movio cada cita, cuando y por que.';

-- ------------------------------------------------------------
-- Las citas que ya existen arrancan con su fila de alta, para que el historial
-- no empiece en blanco. No se pueden inventar las confirmaciones pasadas: de
-- esas no quedo rastro y no lo va a haber.
-- ------------------------------------------------------------
INSERT INTO cambio_estado_cita (cita_id, estado_anterior, estado_nuevo, fecha, usuario_id, motivo)
SELECT id, NULL, 'PENDIENTE', created_at, created_by, 'Cita dada de alta'
  FROM cita;
