-- ============================================================
-- V22 - Bitacora de actividad por persona
-- ============================================================
-- El rastro de la jornada se sacaba de lo que ya habia: cambios de estado,
-- created_by y updated_by. Se escapaba todo el trabajo que no mueve estados:
-- escribir el diagnostico, meter horas y piezas, tocar precios y descuentos.
-- Un tecnico podia pasarse la manana diagnosticando una orden que otro ya
-- habia puesto en diagnostico y en sus horas no salia nada. Y de las
-- ediciones de fichas solo sobrevivia la ultima, porque updated_by se pisa.
--
-- Una fila por cosa hecha, append-only, con quien y cuando.
-- ============================================================

CREATE TABLE actividad_usuario (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   BIGINT       NOT NULL,
    fecha        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    tipo         VARCHAR(20)  NOT NULL,
    destino_tipo VARCHAR(20),
    destino_id   BIGINT,
    texto        VARCHAR(500) NOT NULL,

    CONSTRAINT fk_actividad_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_actividad_usuario_fecha ON actividad_usuario (usuario_id, fecha);

CREATE TRIGGER tg_actividad_usuario_inmutable
    BEFORE UPDATE OR DELETE ON actividad_usuario
    FOR EACH ROW EXECUTE FUNCTION fn_bloquear_modificacion();

COMMENT ON TABLE actividad_usuario IS
    'Bitacora append-only del trabajo de cada persona que no deja rastro en otras tablas.';
