-- =====================================================================
-- V23 - Facturas del programa anterior: archivo de solo consulta
-- =====================================================================
-- Copia de las facturas que el taller emitio con otro programa antes de
-- usar este (NEXTGO). A proposito NO se mezclan con las de V5: no llevan
-- numeracion de este programa, no entran en la cadena de huellas, ni en el
-- libro registro, ni en la exportacion a la gestoria. Ya las emitio y las
-- declaro el otro programa; meterlas alli seria emitirlas dos veces.
--
-- Las originales, las que cuentan ante Hacienda, las conserva el taller en
-- PDF. Aqui se guarda una copia para verlas en la ficha del cliente y de la
-- moto, y para que el historial de la moto salga completo.
--
-- La aplicacion solo las lee. Se cargan una vez con el script
-- import_facturas_nextgo.py, que las saca del PDF del programa anterior.
-- ---------------------------------------------------------------------
CREATE TABLE factura_anterior (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Programa del que viene y numero tal cual lo imprimio: juntos la
    -- identifican, y permiten volver a cargar el fichero sin duplicar nada.
    origen          VARCHAR(40)   NOT NULL,
    numero          VARCHAR(40)   NOT NULL,
    fecha           DATE          NOT NULL,
    cliente_id      BIGINT        NOT NULL,
    -- Nula si no se sabe de que moto era: la factura no lo decia.
    moto_id         BIGINT,
    receptor_nombre VARCHAR(250)  NOT NULL,
    receptor_nif    VARCHAR(20),
    base_imponible  NUMERIC(12,2) NOT NULL,
    total_iva       NUMERIC(12,2) NOT NULL,
    total           NUMERIC(12,2) NOT NULL,
    -- La factura original, tal cual la emitio el otro programa.
    pdf             BYTEA         NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_factura_anterior_numero  UNIQUE (origen, numero),
    CONSTRAINT ck_factura_anterior_totales CHECK (total = base_imponible + total_iva),
    CONSTRAINT fk_factura_anterior_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_factura_anterior_moto    FOREIGN KEY (moto_id)    REFERENCES moto (id)
);

CREATE INDEX ix_factura_anterior_cliente ON factura_anterior (cliente_id, fecha DESC);
CREATE INDEX ix_factura_anterior_moto    ON factura_anterior (moto_id, fecha DESC) WHERE moto_id IS NOT NULL;

COMMENT ON TABLE factura_anterior IS 'Facturas emitidas con el programa anterior. Solo consulta: fuera de la numeracion, la cadena y los libros de este programa.';


-- Las lineas se guardan como datos, y no solo dentro del PDF, para que el
-- historial de la moto pueda contar que se le hizo.
CREATE TABLE linea_factura_anterior (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_anterior_id BIGINT        NOT NULL,
    numero_linea        INTEGER       NOT NULL,
    tipo                VARCHAR(20)   NOT NULL,
    codigo              VARCHAR(50),
    descripcion         TEXT          NOT NULL,
    cantidad            NUMERIC(12,3) NOT NULL,
    precio_unitario     NUMERIC(12,4) NOT NULL,
    descuento_pct       NUMERIC(5,2)  NOT NULL DEFAULT 0,
    -- Sin IVA, como la columna «Total» de la factura original.
    importe             NUMERIC(12,2) NOT NULL,

    CONSTRAINT uq_linea_factura_anterior      UNIQUE (factura_anterior_id, numero_linea),
    CONSTRAINT ck_linea_factura_anterior_tipo CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA')),
    CONSTRAINT fk_linea_factura_anterior      FOREIGN KEY (factura_anterior_id)
        REFERENCES factura_anterior (id) ON DELETE CASCADE
);


-- ---------------------------------------------------------------------
-- Mismo blindaje que V8 y V13 en Supabase: sin el, estas serian las unicas
-- tablas sin la segunda barrera. En PostgreSQL estandar no hace nada.
-- ---------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        ALTER TABLE public.factura_anterior       ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.factura_anterior       FORCE  ROW LEVEL SECURITY;
        ALTER TABLE public.linea_factura_anterior ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.linea_factura_anterior FORCE  ROW LEVEL SECURITY;
        RAISE NOTICE 'Blindaje aplicado a factura_anterior y linea_factura_anterior.';
    ELSE
        RAISE NOTICE 'Roles de Supabase no encontrados: se omite el blindaje.';
    END IF;
END;
$$;
