-- =====================================================================
-- Tasas y pluses
--
-- La tasa de neumaticos de la V18 era una sola regla: una familia y una
-- pieza del almacen que hacia de tasa. El taller quiere mas: tasas para
-- cualquier grupo o para una pieza concreta, con el importe que diga el, y
-- pluses —descuentos fijos— sobre productos concretos o grupos enteros.
--
-- Decisiones:
--
--   * Una regla apunta a un grupo entero O a una pieza concreta, nunca a
--     las dos. Si hay de ambas, la de la pieza manda sobre la de su grupo.
--   * La tasa deja de ser una pieza del almacen y pasa a ser un importe. Una
--     pieza obligaba a tener existencias de algo que no esta en ninguna
--     estanteria, y sin ellas la orden se quedaba esperando piezas. Por eso
--     su linea es de un tipo propio, TASA: no sale del almacen y no cuenta
--     como horas de mano de obra.
--   * El plus es un descuento en tanto por ciento que se pone solo en la
--     linea de la pieza al anadirla. Despues se retoca a mano como cualquier
--     otro descuento.
-- =====================================================================

CREATE TABLE regla_cobro (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo        VARCHAR(10)   NOT NULL,
    familia     VARCHAR(60),
    pieza_id    BIGINT        REFERENCES pieza (id),
    -- El texto de la linea de la tasa. En un plus no sale en ningun sitio.
    concepto    VARCHAR(300),
    -- Euros por unidad en una tasa; tanto por ciento en un plus.
    valor       NUMERIC(12,2) NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by  BIGINT,
    version     INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT ck_regla_cobro_tipo     CHECK (tipo IN ('TASA', 'PLUS')),
    CONSTRAINT ck_regla_cobro_objetivo CHECK ((familia IS NULL) <> (pieza_id IS NULL)),
    CONSTRAINT ck_regla_cobro_tasa     CHECK (tipo <> 'TASA' OR (concepto IS NOT NULL AND valor > 0)),
    CONSTRAINT ck_regla_cobro_plus     CHECK (tipo <> 'PLUS' OR (valor > 0 AND valor <= 100))
);

-- Dos tasas para lo mismo cobrarian dos veces; dos pluses no se sabria cual vale.
CREATE UNIQUE INDEX ux_regla_cobro ON regla_cobro
    (tipo, COALESCE(LOWER(familia), ''), COALESCE(pieza_id, 0));

COMMENT ON TABLE  regla_cobro         IS 'Tasas y pluses que se aplican solos al anadir una pieza a una orden.';
COMMENT ON COLUMN regla_cobro.familia IS 'Grupo de piezas al que se aplica. Nulo si la regla es de una pieza concreta.';
COMMENT ON COLUMN regla_cobro.valor   IS 'TASA: euros por unidad, sin IVA. PLUS: descuento en tanto por ciento.';


-- ---------------------------------------------------------------------
-- La linea de tasa: sin pieza, como la mano de obra, pero sin ser horas.
-- ---------------------------------------------------------------------
ALTER TABLE linea_ot DROP CONSTRAINT ck_linea_ot_tipo;
ALTER TABLE linea_ot DROP CONSTRAINT ck_linea_ot_pieza;
ALTER TABLE linea_ot ADD CONSTRAINT ck_linea_ot_tipo
    CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA', 'TASA'));
ALTER TABLE linea_ot ADD CONSTRAINT ck_linea_ot_pieza
    CHECK ((tipo = 'PIEZA') = (pieza_id IS NOT NULL));

ALTER TABLE linea_factura DROP CONSTRAINT ck_linea_factura_tipo;
ALTER TABLE linea_factura ADD CONSTRAINT ck_linea_factura_tipo
    CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA', 'TASA'));


-- ---------------------------------------------------------------------
-- La tasa de neumaticos que hubiera configurada pasa a ser una regla, con
-- el precio que tenia su pieza. Las ordenes ya abiertas conservan su linea
-- de pieza tal cual.
-- ---------------------------------------------------------------------
INSERT INTO regla_cobro (tipo, familia, concepto, valor)
SELECT 'TASA', c.familia_neumaticos, p.descripcion, p.precio_venta
  FROM configuracion_taller c
  JOIN pieza p ON p.id = c.pieza_tasa_neumatico_id
 WHERE c.familia_neumaticos IS NOT NULL
   AND p.precio_venta > 0;

ALTER TABLE configuracion_taller
    DROP COLUMN familia_neumaticos,
    DROP COLUMN pieza_tasa_neumatico_id;


-- Mismo blindaje que V8, V13 y V23 en Supabase. En PostgreSQL estandar no hace nada.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        ALTER TABLE public.regla_cobro ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.regla_cobro FORCE  ROW LEVEL SECURITY;
        RAISE NOTICE 'Blindaje aplicado a regla_cobro.';
    ELSE
        RAISE NOTICE 'Roles de Supabase no encontrados: se omite el blindaje.';
    END IF;
END;
$$;
