-- =====================================================================
-- V29 - Solicitudes que llegan desde la web publica
-- =====================================================================
-- La web del taller (19racingmotorsport.com) tiene un formulario donde el
-- cliente pide cita o presupuesto, con hasta tres fotos. Cada envio entra aqui
-- como una solicitud pendiente, y mostrador la atiende: le manda un
-- presupuesto (por WhatsApp o email), le da cita en la agenda, la marca como
-- atendida o la descarta.
--
-- A proposito NO crea clientes, motos ni citas por su cuenta. Lo que escribe un
-- desconocido en un formulario no se mezcla con los datos del taller hasta que
-- alguien lo ha leido: evita duplicados, datos mal escritos y spam.
-- ---------------------------------------------------------------------
CREATE TABLE solicitud_web (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identificador que pone la web. Si reintenta el envio, la solicitud no
    -- se duplica.
    referencia      VARCHAR(40)  NOT NULL,
    tipo            VARCHAR(20)  NOT NULL,
    estado          VARCHAR(20)  NOT NULL,
    recibida_en     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Idioma en que se relleno: en el que habra que contestar.
    idioma          VARCHAR(2)   NOT NULL,

    nombre          VARCHAR(120) NOT NULL,
    telefono        VARCHAR(30)  NOT NULL,
    email           VARCHAR(160),
    marca           VARCHAR(60)  NOT NULL,
    modelo          VARCHAR(60)  NOT NULL,
    matricula       VARCHAR(20),
    necesita        TEXT         NOT NULL,
    fecha_preferida DATE,
    -- Cuantas fotos trae. Las fotos no cambian despues de llegar, y asi la
    -- bandeja sabe cuantas pedir sin cargar las imagenes para contarlas.
    num_fotos       SMALLINT     NOT NULL DEFAULT 0,

    -- Presupuesto que se le mando, si se le mando. Se puede volver a mandar
    -- corregido: aqui queda el ultimo.
    presupuesto_importe NUMERIC(10,2),
    presupuesto_detalle TEXT,
    presupuesto_canal   VARCHAR(10),
    presupuestada_en    TIMESTAMPTZ,
    presupuestada_por   BIGINT,

    -- Cita que se le dio, si se atendio asi.
    cita_id         BIGINT,
    -- Lo que apunta quien la cierra: «presupuesto por telefono, 180 €».
    nota            VARCHAR(500),
    atendida_en     TIMESTAMPTZ,
    atendida_por    BIGINT,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    version         INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_solicitud_web_referencia UNIQUE (referencia),
    CONSTRAINT ck_solicitud_web_tipo   CHECK (tipo   IN ('CITA', 'PRESUPUESTO')),
    CONSTRAINT ck_solicitud_web_estado CHECK (estado IN ('PENDIENTE', 'PRESUPUESTADA', 'ATENDIDA', 'DESCARTADA')),
    CONSTRAINT ck_solicitud_web_idioma CHECK (idioma IN ('es', 'ca', 'en', 'fr')),
    CONSTRAINT ck_solicitud_web_fotos  CHECK (num_fotos BETWEEN 0 AND 3),
    -- Una solicitud cerrada dice cuando y quien la cerro; una abierta, no.
    CONSTRAINT ck_solicitud_web_cierre CHECK ((estado IN ('PENDIENTE', 'PRESUPUESTADA')) = (atendida_en IS NULL)),
    -- Presupuestada es haber mandado un presupuesto, con su importe.
    CONSTRAINT ck_solicitud_web_presupuesto CHECK (estado <> 'PRESUPUESTADA' OR presupuesto_importe IS NOT NULL),
    CONSTRAINT ck_solicitud_web_importe CHECK (presupuesto_importe IS NULL OR presupuesto_importe > 0),
    CONSTRAINT ck_solicitud_web_canal   CHECK (presupuesto_canal IS NULL OR presupuesto_canal IN ('WHATSAPP', 'EMAIL')),
    CONSTRAINT fk_solicitud_web_cita     FOREIGN KEY (cita_id)      REFERENCES cita (id),
    CONSTRAINT fk_solicitud_web_atendida FOREIGN KEY (atendida_por) REFERENCES usuario (id),
    CONSTRAINT fk_solicitud_web_presupuestada FOREIGN KEY (presupuestada_por) REFERENCES usuario (id)
);

-- La bandeja se mira siempre por estado y de la mas nueva a la mas vieja.
CREATE INDEX ix_solicitud_web_estado ON solicitud_web (estado, recibida_en DESC);

COMMENT ON TABLE solicitud_web IS
    'Citas y presupuestos pedidos desde la web publica. Se atienden a mano desde la bandeja.';


-- Fotos que adjunta el cliente: el golpe, el carenado, la averia. Se guardan en
-- la base, como los PDF de las facturas anteriores, para que entren en la copia
-- de seguridad sin montar nada mas.
CREATE TABLE solicitud_web_foto (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id   BIGINT      NOT NULL,
    orden          SMALLINT    NOT NULL,
    tipo_contenido VARCHAR(20) NOT NULL,
    datos          BYTEA       NOT NULL,

    CONSTRAINT uq_solicitud_web_foto_orden UNIQUE (solicitud_id, orden),
    CONSTRAINT ck_solicitud_web_foto_orden CHECK (orden BETWEEN 1 AND 3),
    CONSTRAINT ck_solicitud_web_foto_tipo  CHECK (tipo_contenido IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT fk_solicitud_web_foto FOREIGN KEY (solicitud_id) REFERENCES solicitud_web (id) ON DELETE CASCADE
);


-- Atender las solicitudes es cosa de quien lleva la agenda.
INSERT INTO rol_permiso (rol_id, permiso)
SELECT rol_id, 'SOLICITUDES_WEB'
FROM rol_permiso
WHERE permiso = 'AGENDA_GESTIONAR'
ON CONFLICT DO NOTHING;


-- Mismo blindaje que V8, V13, V23 y V25 en Supabase. En PostgreSQL estandar no hace nada.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        ALTER TABLE public.solicitud_web      ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.solicitud_web      FORCE  ROW LEVEL SECURITY;
        ALTER TABLE public.solicitud_web_foto ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.solicitud_web_foto FORCE  ROW LEVEL SECURITY;
        RAISE NOTICE 'Blindaje aplicado a solicitud_web y solicitud_web_foto.';
    ELSE
        RAISE NOTICE 'Roles de Supabase no encontrados: se omite el blindaje.';
    END IF;
END;
$$;
