-- =====================================================================
-- V2 - Clientes y motos
-- =====================================================================


-- ---------------------------------------------------------------------
-- Clientes
-- ---------------------------------------------------------------------
-- Los datos fiscales (documento + direccion completa) pueden faltar al dar
-- de alta a un cliente que entra por primera vez, pero son OBLIGATORIOS
-- antes de emitir una factura. La comprobacion se hace en el dominio
-- (Cliente.tieneDatosFiscalesCompletos) porque hasta ese momento es legitimo
-- tener una ficha incompleta.
CREATE TABLE cliente (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    apellidos       VARCHAR(150),
    tipo_documento  VARCHAR(10),
    documento       VARCHAR(20),
    direccion       VARCHAR(200),
    codigo_postal   VARCHAR(10),
    ciudad          VARCHAR(100),
    provincia       VARCHAR(100),
    pais            VARCHAR(60)  NOT NULL DEFAULT 'Espana',
    email           VARCHAR(150),
    telefono        VARCHAR(30),
    observaciones   TEXT,
    -- Baja logica: los clientes nunca se borran fisicamente porque estan
    -- referenciados por ordenes de trabajo y facturas.
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_baja      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    version         INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_cliente_tipo_documento CHECK (tipo_documento IS NULL OR tipo_documento IN ('NIF', 'CIF', 'NIE', 'PASAPORTE', 'OTRO')),
    CONSTRAINT ck_cliente_baja           CHECK ((activo AND fecha_baja IS NULL) OR (NOT activo AND fecha_baja IS NOT NULL)),
    CONSTRAINT fk_cliente_created_by     FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_cliente_updated_by     FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

-- El documento es opcional, pero cuando existe no puede repetirse.
-- Se indexa en mayusculas para que "12345678z" y "12345678Z" colisionen.
CREATE UNIQUE INDEX ux_cliente_documento ON cliente (UPPER(documento)) WHERE documento IS NOT NULL;

-- Busqueda habitual desde mostrador: por apellidos/nombre y por telefono.
CREATE INDEX ix_cliente_nombre   ON cliente (UPPER(apellidos), UPPER(nombre));
CREATE INDEX ix_cliente_telefono ON cliente (telefono);
CREATE INDEX ix_cliente_activo   ON cliente (activo);

COMMENT ON TABLE  cliente            IS 'Clientes del taller. Baja logica: nunca se borran fisicamente.';
COMMENT ON COLUMN cliente.documento  IS 'NIF/CIF/NIE. Opcional en el alta, obligatorio para poder facturar.';
COMMENT ON COLUMN cliente.fecha_baja IS 'Momento de la baja logica. Coherente con activo via ck_cliente_baja.';


-- ---------------------------------------------------------------------
-- Motos
-- ---------------------------------------------------------------------
CREATE TABLE moto (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id      BIGINT        NOT NULL,
    matricula       VARCHAR(15)   NOT NULL,
    marca           VARCHAR(60)   NOT NULL,
    modelo          VARCHAR(100)  NOT NULL,
    anio            INTEGER,
    cilindrada      INTEGER,
    color           VARCHAR(50),
    numero_bastidor VARCHAR(30),
    -- Kilometraje conocido mas reciente. Se actualiza al abrir cada OT y
    -- nunca puede retroceder (validado en el dominio en la fase 3).
    km_actual       INTEGER       NOT NULL DEFAULT 0,
    observaciones   TEXT,
    activo          BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_baja      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by      BIGINT,
    version         INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT fk_moto_cliente     FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT ck_moto_anio        CHECK (anio IS NULL OR (anio >= 1885 AND anio <= 2200)),
    CONSTRAINT ck_moto_cilindrada  CHECK (cilindrada IS NULL OR cilindrada > 0),
    CONSTRAINT ck_moto_km          CHECK (km_actual >= 0),
    CONSTRAINT ck_moto_baja        CHECK ((activo AND fecha_baja IS NULL) OR (NOT activo AND fecha_baja IS NOT NULL)),
    CONSTRAINT fk_moto_created_by  FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_moto_updated_by  FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

-- La matricula identifica al vehiculo de forma unica en todo el taller.
CREATE UNIQUE INDEX ux_moto_matricula ON moto (UPPER(matricula));
-- El bastidor es opcional pero tambien unico cuando se conoce.
CREATE UNIQUE INDEX ux_moto_bastidor  ON moto (UPPER(numero_bastidor)) WHERE numero_bastidor IS NOT NULL;

CREATE INDEX ix_moto_cliente ON moto (cliente_id);
CREATE INDEX ix_moto_marca   ON moto (UPPER(marca), UPPER(modelo));

COMMENT ON TABLE  moto           IS 'Motos del taller. El historial completo se obtiene via orden_trabajo.moto_id.';
COMMENT ON COLUMN moto.km_actual IS 'Ultimo kilometraje registrado. Se actualiza con el km de entrada de cada OT.';
