-- ============================================================
-- V31 - Historial de cambios de cada jornada
-- ============================================================
-- La jornada ya guardaba lo que se fichó y, aparte, la correccion del
-- administrador. Pero solo UNA: si se corregia dos veces, la segunda pisaba
-- a la primera y ya no se sabia que horas habia antes. Eso no es un rastro.
--
-- Se copia el patron del historial de la OT y de la cita: una fila por cambio,
-- append-only, con las horas de antes, las de despues, quien y por que.
-- ============================================================

CREATE TABLE cambio_fichaje (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fichaje_id      BIGINT       NOT NULL,

    -- Las horas que contaban justo antes del cambio. Salida nula: la jornada
    -- estaba abierta (se fue sin fichar la salida).
    inicio_anterior TIMESTAMPTZ  NOT NULL,
    fin_anterior    TIMESTAMPTZ,

    inicio_nuevo    TIMESTAMPTZ  NOT NULL,
    fin_nuevo       TIMESTAMPTZ  NOT NULL,

    motivo          VARCHAR(300) NOT NULL,
    usuario_id      BIGINT,
    fecha           TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_cambio_fichaje_fichaje FOREIGN KEY (fichaje_id) REFERENCES fichaje (id),
    CONSTRAINT fk_cambio_fichaje_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT ck_cambio_fichaje_orden CHECK (fin_nuevo >= inicio_nuevo)
);

-- Siempre se pide el de una jornada concreta, en orden.
CREATE INDEX ix_cambio_fichaje_fichaje ON cambio_fichaje (fichaje_id, fecha);

-- Un cambio mal hecho no se borra: se corrige con el siguiente.
CREATE TRIGGER tg_cambio_fichaje_inmutable
    BEFORE UPDATE OR DELETE ON cambio_fichaje
    FOR EACH ROW EXECUTE FUNCTION fn_bloquear_modificacion();

COMMENT ON TABLE cambio_fichaje IS
    'Historial append-only de las horas de cada jornada: que habia antes, que se puso, quien y por que.';

-- ------------------------------------------------------------
-- Las jornadas ya corregidas o cerradas a mano arrancan con su cambio. Solo
-- se puede rescatar el ultimo: los anteriores se pisaron y no hay de donde
-- sacarlos.
-- ------------------------------------------------------------
INSERT INTO cambio_fichaje (fichaje_id, inicio_anterior, fin_anterior, inicio_nuevo, fin_nuevo,
                            motivo, usuario_id, fecha)
SELECT id,
       inicio,
       CASE WHEN cerrada_por_olvido THEN NULL ELSE fin END,
       COALESCE(inicio_corregido, inicio),
       COALESCE(fin_corregido, fin),
       motivo_correccion,
       corregido_por,
       corregido_en
  FROM fichaje
 WHERE corregido_en IS NOT NULL
   AND motivo_correccion IS NOT NULL
   AND fin IS NOT NULL;
