-- =====================================================================
-- V32 - Presupuesto con lineas para las solicitudes de la web
-- =====================================================================
-- Hasta ahora a quien pedia presupuesto por la web se le mandaba un importe y
-- un texto. Ahora se le monta un presupuesto de verdad, como el de una orden de
-- trabajo: mano de obra y material del almacen, con su IVA, sus descuentos y
-- el mismo PDF.
--
-- Va aparte de la orden de trabajo a proposito: quien pide presupuesto aun no
-- ha traido la moto, y abrir una orden exige darla de alta con su bastidor. Si
-- el cliente acepta, entonces si se abre la orden con estas mismas lineas.
-- ---------------------------------------------------------------------
ALTER TABLE solicitud_web
    -- Precio de la hora de este presupuesto: se toma el del taller al empezarlo.
    ADD COLUMN tarifa_hora      NUMERIC(12,2),
    -- IVA impuesto a todo el presupuesto, o nulo si cada linea lleva el suyo.
    ADD COLUMN tipo_iva         VARCHAR(20),
    -- La orden que se abrio cuando el cliente acepto.
    ADD COLUMN orden_trabajo_id BIGINT,
    ADD CONSTRAINT ck_solicitud_web_tarifa   CHECK (tarifa_hora IS NULL OR tarifa_hora > 0),
    ADD CONSTRAINT fk_solicitud_web_tipo_iva FOREIGN KEY (tipo_iva)         REFERENCES tipo_iva (codigo),
    ADD CONSTRAINT fk_solicitud_web_orden    FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo (id);


-- Las lineas se valoran exactamente igual que las de una orden (linea_ot):
-- mismos redondeos, calculados por la base de datos.
CREATE TABLE linea_presupuesto_web (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id     BIGINT        NOT NULL,
    numero_linea     INTEGER       NOT NULL,
    tipo             VARCHAR(20)   NOT NULL,
    descripcion      VARCHAR(300)  NOT NULL,
    pieza_id         BIGINT,
    cantidad         NUMERIC(12,3) NOT NULL,
    precio_unitario  NUMERIC(12,4) NOT NULL,
    descuento_pct    NUMERIC(5,2)  NOT NULL DEFAULT 0,
    tipo_iva         VARCHAR(20)   NOT NULL,
    porcentaje_iva   NUMERIC(5,2)  NOT NULL,

    base_imponible NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)) STORED,
    cuota_iva      NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,
    total          NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)
         + ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    version    INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT uq_linea_presupuesto_web_numero UNIQUE (solicitud_id, numero_linea),
    CONSTRAINT ck_linea_presupuesto_web_tipo   CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA', 'TASA')),
    CONSTRAINT ck_linea_presupuesto_web_pieza  CHECK ((tipo = 'PIEZA') = (pieza_id IS NOT NULL)),
    CONSTRAINT ck_linea_presupuesto_web_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_linea_presupuesto_web_precio    CHECK (precio_unitario >= 0),
    CONSTRAINT ck_linea_presupuesto_web_descuento CHECK (descuento_pct >= 0 AND descuento_pct <= 100),
    CONSTRAINT ck_linea_presupuesto_web_iva       CHECK (porcentaje_iva >= 0 AND porcentaje_iva <= 100),
    CONSTRAINT fk_linea_presupuesto_web_solicitud FOREIGN KEY (solicitud_id) REFERENCES solicitud_web (id) ON DELETE CASCADE,
    CONSTRAINT fk_linea_presupuesto_web_pieza     FOREIGN KEY (pieza_id)     REFERENCES pieza (id),
    CONSTRAINT fk_linea_presupuesto_web_tipo_iva  FOREIGN KEY (tipo_iva)     REFERENCES tipo_iva (codigo),
    CONSTRAINT fk_linea_presupuesto_web_created_by FOREIGN KEY (created_by)  REFERENCES usuario (id),
    CONSTRAINT fk_linea_presupuesto_web_updated_by FOREIGN KEY (updated_by)  REFERENCES usuario (id)
);

CREATE INDEX ix_linea_presupuesto_web_pieza ON linea_presupuesto_web (pieza_id) WHERE pieza_id IS NOT NULL;


-- Mismo blindaje que V29 en Supabase. En PostgreSQL estandar no hace nada.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        ALTER TABLE public.linea_presupuesto_web ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.linea_presupuesto_web FORCE  ROW LEVEL SECURITY;
        RAISE NOTICE 'Blindaje aplicado a linea_presupuesto_web.';
    ELSE
        RAISE NOTICE 'Roles de Supabase no encontrados: se omite el blindaje.';
    END IF;
END;
$$;
