-- =====================================================================
-- V3 - Inventario: proveedores, piezas y movimientos de stock
-- =====================================================================


-- ---------------------------------------------------------------------
-- Proveedores
-- ---------------------------------------------------------------------
CREATE TABLE proveedor (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(150) NOT NULL,
    nif           VARCHAR(20),
    direccion     VARCHAR(200),
    codigo_postal VARCHAR(10),
    ciudad        VARCHAR(100),
    provincia     VARCHAR(100),
    telefono      VARCHAR(30),
    email         VARCHAR(150),
    observaciones TEXT,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_baja    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by    BIGINT,
    version       INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT ck_proveedor_baja       CHECK ((activo AND fecha_baja IS NULL) OR (NOT activo AND fecha_baja IS NOT NULL)),
    CONSTRAINT fk_proveedor_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_proveedor_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

CREATE UNIQUE INDEX ux_proveedor_nif ON proveedor (UPPER(nif)) WHERE nif IS NOT NULL;

COMMENT ON TABLE proveedor IS 'Proveedores de recambios. Baja logica.';


-- ---------------------------------------------------------------------
-- Piezas (catalogo de recambios)
-- ---------------------------------------------------------------------
CREATE TABLE pieza (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(50)   NOT NULL,
    descripcion    VARCHAR(200)  NOT NULL,
    marca          VARCHAR(60),
    ubicacion      VARCHAR(50),
    -- stock_actual NO se edita nunca de forma directa: lo mantiene en exclusiva
    -- el trigger tg_movimiento_stock_aplicar (ver V6). Un trigger de guarda
    -- rechaza cualquier UPDATE que intente tocarlo por otra via.
    stock_actual   NUMERIC(12,3) NOT NULL DEFAULT 0,
    stock_minimo   NUMERIC(12,3) NOT NULL DEFAULT 0,
    precio_coste   NUMERIC(12,4) NOT NULL DEFAULT 0,
    precio_venta   NUMERIC(12,4) NOT NULL DEFAULT 0,
    tipo_iva       VARCHAR(20)   NOT NULL DEFAULT 'GENERAL',
    proveedor_id   BIGINT,
    unidad_medida  VARCHAR(10)   NOT NULL DEFAULT 'UD',
    observaciones  TEXT,
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_baja     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by     BIGINT,
    version        INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT ck_pieza_stock_minimo CHECK (stock_minimo >= 0),
    -- El stock nunca puede quedar negativo: si no hay piezas suficientes, la OT
    -- pasa a ESPERANDO_PIEZAS en lugar de permitir un descubierto.
    CONSTRAINT ck_pieza_stock_actual CHECK (stock_actual >= 0),
    CONSTRAINT ck_pieza_precios      CHECK (precio_coste >= 0 AND precio_venta >= 0),
    CONSTRAINT ck_pieza_baja         CHECK ((activo AND fecha_baja IS NULL) OR (NOT activo AND fecha_baja IS NOT NULL)),
    CONSTRAINT fk_pieza_tipo_iva     FOREIGN KEY (tipo_iva)     REFERENCES tipo_iva (codigo),
    CONSTRAINT fk_pieza_proveedor    FOREIGN KEY (proveedor_id) REFERENCES proveedor (id),
    CONSTRAINT fk_pieza_created_by   FOREIGN KEY (created_by)   REFERENCES usuario (id),
    CONSTRAINT fk_pieza_updated_by   FOREIGN KEY (updated_by)   REFERENCES usuario (id)
);

CREATE UNIQUE INDEX ux_pieza_sku ON pieza (UPPER(sku));

CREATE INDEX ix_pieza_descripcion ON pieza (UPPER(descripcion));
CREATE INDEX ix_pieza_proveedor   ON pieza (proveedor_id);
-- Indice de apoyo para el listado de piezas bajo minimos.
CREATE INDEX ix_pieza_bajo_minimo ON pieza (id) WHERE activo AND stock_actual <= stock_minimo;

COMMENT ON TABLE  pieza              IS 'Catalogo de recambios. Baja logica.';
COMMENT ON COLUMN pieza.stock_actual IS 'DERIVADO. Solo lo escribe el trigger de movimientos de stock; cualquier otro UPDATE se rechaza.';
COMMENT ON COLUMN pieza.precio_venta IS 'Precio de catalogo. Se congela como precio_unitario al anadir una linea a una OT.';


-- ---------------------------------------------------------------------
-- Movimientos de stock
-- ---------------------------------------------------------------------
-- Libro de movimientos: es la unica fuente de verdad del inventario.
-- pieza.stock_actual es un acumulado cacheado que se deriva de esta tabla.
-- Los movimientos son INMUTABLES: no se editan ni se borran (ver V6). Una
-- entrada equivocada se corrige con un movimiento de AJUSTE de signo contrario.
CREATE TABLE movimiento_stock (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pieza_id              BIGINT        NOT NULL,
    tipo                  VARCHAR(20)   NOT NULL,
    -- Cantidad CON SIGNO: positiva suma stock, negativa lo resta.
    cantidad              NUMERIC(12,3) NOT NULL,
    -- Instantanea del stock antes y despues, calculada por el trigger.
    -- Permite auditar la trazabilidad sin recalcular toda la serie.
    stock_anterior        NUMERIC(12,3) NOT NULL DEFAULT 0,
    stock_resultante      NUMERIC(12,3) NOT NULL DEFAULT 0,
    fecha                 TIMESTAMPTZ   NOT NULL DEFAULT now(),
    usuario_id            BIGINT,
    -- Relacion con la OT que consume la pieza (solo en SALIDA / DEVOLUCION).
    -- Las claves ajenas se anaden en V4, cuando ya existen esas tablas.
    orden_trabajo_id      BIGINT,
    linea_ot_id           BIGINT,
    motivo                VARCHAR(300),
    documento_proveedor   VARCHAR(60),
    precio_coste_unitario NUMERIC(12,4),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_movimiento_tipo CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'DEVOLUCION')),
    -- Un movimiento de cantidad cero no aporta nada y ensucia el libro.
    CONSTRAINT ck_movimiento_cantidad_no_cero CHECK (cantidad <> 0),
    -- El signo tiene que ser coherente con el tipo de movimiento.
    -- El AJUSTE es el unico que admite ambos signos (inventario fisico).
    CONSTRAINT ck_movimiento_signo CHECK (
        (tipo = 'ENTRADA'    AND cantidad > 0) OR
        (tipo = 'SALIDA'     AND cantidad < 0) OR
        (tipo = 'DEVOLUCION' AND cantidad > 0) OR
        (tipo = 'AJUSTE')
    ),
    -- Toda salida o devolucion asociada a una OT debe indicar la OT.
    CONSTRAINT ck_movimiento_motivo CHECK (
        tipo <> 'AJUSTE' OR (motivo IS NOT NULL AND length(trim(motivo)) > 0)
    ),
    CONSTRAINT fk_movimiento_pieza   FOREIGN KEY (pieza_id)   REFERENCES pieza (id),
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_movimiento_pieza_fecha ON movimiento_stock (pieza_id, fecha DESC, id DESC);
CREATE INDEX ix_movimiento_orden       ON movimiento_stock (orden_trabajo_id) WHERE orden_trabajo_id IS NOT NULL;
CREATE INDEX ix_movimiento_tipo_fecha  ON movimiento_stock (tipo, fecha DESC);

COMMENT ON TABLE  movimiento_stock            IS 'Libro inmutable de movimientos. Unica fuente de verdad del stock.';
COMMENT ON COLUMN movimiento_stock.cantidad   IS 'Cantidad con signo: ENTRADA/DEVOLUCION > 0, SALIDA < 0, AJUSTE cualquiera.';
COMMENT ON COLUMN movimiento_stock.motivo     IS 'Obligatorio en los AJUSTE para justificar la correccion de inventario.';
