-- =====================================================================
-- V4 - Ordenes de trabajo, sus lineas y el historial de estados
-- =====================================================================


-- ---------------------------------------------------------------------
-- Contador de numeracion de OT por ejercicio
-- ---------------------------------------------------------------------
-- No se usa una SEQUENCE porque las secuencias no son transaccionales y
-- dejan huecos al hacer rollback. Aqui el contador se incrementa dentro de
-- la misma transaccion que inserta la OT: si esta falla, el numero se libera.
CREATE TABLE contador_ot (
    ejercicio     INTEGER PRIMARY KEY,
    ultimo_numero INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT ck_contador_ot_numero CHECK (ultimo_numero >= 0)
);

COMMENT ON TABLE contador_ot IS 'Ultimo numero de OT asignado por ejercicio. Se bloquea con SELECT ... FOR UPDATE al abrir una OT.';


-- ---------------------------------------------------------------------
-- Ordenes de trabajo
-- ---------------------------------------------------------------------
CREATE TABLE orden_trabajo (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ejercicio             INTEGER       NOT NULL,
    numero                INTEGER       NOT NULL,
    -- Numero correlativo visible para el cliente y el mostrador: OT-2026-00042
    codigo                VARCHAR(20)   GENERATED ALWAYS AS
                              ('OT-' || ejercicio::text || '-' || LPAD(numero::text, 5, '0')) STORED,
    moto_id               BIGINT        NOT NULL,
    -- Propietario en el momento de la entrada. Se guarda ademas de moto.cliente_id
    -- para que un cambio de propietario no reescriba el historial de la OT.
    cliente_id            BIGINT        NOT NULL,
    fecha_entrada         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_estimada_salida DATE,
    fecha_real_salida     TIMESTAMPTZ,
    km_entrada            INTEGER       NOT NULL,
    problema_reportado    TEXT          NOT NULL,
    diagnostico           TEXT,
    tecnico_id            BIGINT,
    estado                VARCHAR(20)   NOT NULL DEFAULT 'RECIBIDA',
    -- Tarifa de mano de obra congelada al abrir la OT: si sube la tarifa del
    -- taller, las OT ya abiertas mantienen la pactada.
    tarifa_hora           NUMERIC(12,2) NOT NULL,
    fecha_presupuesto     TIMESTAMPTZ,
    fecha_aprobacion      TIMESTAMPTZ,
    aprobado_por          VARCHAR(150),
    motivo_rechazo        TEXT,
    observaciones         TEXT,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by            BIGINT,
    version               INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT uq_orden_numero  UNIQUE (ejercicio, numero),
    CONSTRAINT ck_orden_estado  CHECK (estado IN (
        'RECIBIDA', 'EN_DIAGNOSTICO', 'PRESUPUESTADA', 'APROBADA',
        'EN_REPARACION', 'ESPERANDO_PIEZAS', 'LISTA', 'ENTREGADA', 'RECHAZADA')),
    CONSTRAINT ck_orden_km      CHECK (km_entrada >= 0),
    CONSTRAINT ck_orden_tarifa  CHECK (tarifa_hora >= 0),
    CONSTRAINT ck_orden_numero_positivo CHECK (numero > 0),
    -- La moto solo sale del taller cuando se entrega o cuando se rechaza el presupuesto.
    CONSTRAINT ck_orden_salida_estado   CHECK (fecha_real_salida IS NULL OR estado IN ('ENTREGADA', 'RECHAZADA')),
    CONSTRAINT ck_orden_entregada_fecha CHECK (estado <> 'ENTREGADA' OR fecha_real_salida IS NOT NULL),
    CONSTRAINT ck_orden_fechas          CHECK (fecha_real_salida IS NULL OR fecha_real_salida >= fecha_entrada),
    CONSTRAINT fk_orden_moto       FOREIGN KEY (moto_id)    REFERENCES moto (id),
    CONSTRAINT fk_orden_cliente    FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_orden_tecnico    FOREIGN KEY (tecnico_id) REFERENCES usuario (id),
    CONSTRAINT fk_orden_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_orden_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id),
    CONSTRAINT fk_orden_ejercicio  FOREIGN KEY (ejercicio)  REFERENCES contador_ot (ejercicio)
);

CREATE UNIQUE INDEX ux_orden_codigo ON orden_trabajo (codigo);

CREATE INDEX ix_orden_moto     ON orden_trabajo (moto_id, fecha_entrada DESC);
CREATE INDEX ix_orden_cliente  ON orden_trabajo (cliente_id, fecha_entrada DESC);
-- Tablero del taller: OT abiertas por estado.
CREATE INDEX ix_orden_estado   ON orden_trabajo (estado, fecha_entrada)
    WHERE estado NOT IN ('ENTREGADA', 'RECHAZADA');
-- Bandeja del tecnico: sus OT pendientes.
CREATE INDEX ix_orden_tecnico  ON orden_trabajo (tecnico_id, estado)
    WHERE tecnico_id IS NOT NULL;

COMMENT ON TABLE  orden_trabajo             IS 'Orden de trabajo. En estado ENTREGADA es inmutable (garantizado por trigger en V6).';
COMMENT ON COLUMN orden_trabajo.codigo      IS 'Numero correlativo visible, calculado por la base de datos: OT-<ejercicio>-<numero>.';
COMMENT ON COLUMN orden_trabajo.cliente_id  IS 'Propietario en el momento de la entrada (instantanea, no se recalcula).';
COMMENT ON COLUMN orden_trabajo.tarifa_hora IS 'Tarifa/hora congelada al abrir la OT.';


-- ---------------------------------------------------------------------
-- Historial de cambios de estado
-- ---------------------------------------------------------------------
-- Registro append-only: quien cambio el estado, cuando y por que.
CREATE TABLE cambio_estado_ot (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT      NOT NULL,
    estado_anterior  VARCHAR(20),
    estado_nuevo     VARCHAR(20) NOT NULL,
    fecha            TIMESTAMPTZ NOT NULL DEFAULT now(),
    usuario_id       BIGINT,
    motivo           VARCHAR(300),

    CONSTRAINT ck_cambio_estado_distinto CHECK (estado_anterior IS DISTINCT FROM estado_nuevo),
    CONSTRAINT fk_cambio_orden   FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo (id),
    CONSTRAINT fk_cambio_usuario FOREIGN KEY (usuario_id)       REFERENCES usuario (id)
);

CREATE INDEX ix_cambio_estado_orden ON cambio_estado_ot (orden_trabajo_id, fecha, id);

COMMENT ON TABLE  cambio_estado_ot                 IS 'Historial append-only de transiciones de estado de cada OT.';
COMMENT ON COLUMN cambio_estado_ot.estado_anterior IS 'NULL solo en el registro inicial (apertura de la OT).';


-- ---------------------------------------------------------------------
-- Lineas de la orden de trabajo
-- ---------------------------------------------------------------------
CREATE TABLE linea_ot (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT        NOT NULL,
    numero_linea     INTEGER       NOT NULL,
    tipo             VARCHAR(20)   NOT NULL,
    descripcion      VARCHAR(300)  NOT NULL,
    -- Solo en lineas de tipo PIEZA.
    pieza_id         BIGINT,
    -- En MANO_DE_OBRA la cantidad son horas; en PIEZA, unidades.
    cantidad         NUMERIC(12,3) NOT NULL,
    -- PRECIO CONGELADO: copiado de pieza.precio_venta o de orden.tarifa_hora
    -- en el instante de anadir la linea. Un cambio posterior en el catalogo
    -- no altera esta OT.
    precio_unitario  NUMERIC(12,4) NOT NULL,
    descuento_pct    NUMERIC(5,2)  NOT NULL DEFAULT 0,
    tipo_iva         VARCHAR(20)   NOT NULL,
    -- Porcentaje de IVA tambien congelado en la linea.
    porcentaje_iva   NUMERIC(5,2)  NOT NULL,

    -- Importes calculados por la propia base de datos: imposible que la
    -- aplicacion y la BD discrepen en los totales.
    base_imponible NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)) STORED,
    cuota_iva      NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,
    total          NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)
         + ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT,
    version    INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT uq_linea_ot_numero UNIQUE (orden_trabajo_id, numero_linea),
    CONSTRAINT ck_linea_ot_tipo   CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA')),
    -- Coherencia entre el tipo de linea y la referencia a la pieza.
    CONSTRAINT ck_linea_ot_pieza  CHECK (
        (tipo = 'PIEZA'        AND pieza_id IS NOT NULL) OR
        (tipo = 'MANO_DE_OBRA' AND pieza_id IS NULL)
    ),
    CONSTRAINT ck_linea_ot_cantidad  CHECK (cantidad > 0),
    CONSTRAINT ck_linea_ot_precio    CHECK (precio_unitario >= 0),
    CONSTRAINT ck_linea_ot_descuento CHECK (descuento_pct >= 0 AND descuento_pct <= 100),
    CONSTRAINT ck_linea_ot_iva       CHECK (porcentaje_iva >= 0 AND porcentaje_iva <= 100),
    CONSTRAINT fk_linea_ot_orden      FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo (id) ON DELETE CASCADE,
    CONSTRAINT fk_linea_ot_pieza      FOREIGN KEY (pieza_id)   REFERENCES pieza (id),
    CONSTRAINT fk_linea_ot_tipo_iva   FOREIGN KEY (tipo_iva)   REFERENCES tipo_iva (codigo),
    CONSTRAINT fk_linea_ot_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_linea_ot_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

CREATE INDEX ix_linea_ot_orden ON linea_ot (orden_trabajo_id, numero_linea);
CREATE INDEX ix_linea_ot_pieza ON linea_ot (pieza_id) WHERE pieza_id IS NOT NULL;

COMMENT ON TABLE  linea_ot                 IS 'Lineas de mano de obra y de piezas de una OT, con precios congelados.';
COMMENT ON COLUMN linea_ot.precio_unitario IS 'Congelado al anadir la linea. No se recalcula nunca desde el catalogo.';
COMMENT ON COLUMN linea_ot.base_imponible  IS 'Columna generada por PostgreSQL: cantidad * precio * (1 - descuento).';


-- ---------------------------------------------------------------------
-- Claves ajenas pendientes de movimiento_stock (V3) hacia las OT
-- ---------------------------------------------------------------------
ALTER TABLE movimiento_stock
    ADD CONSTRAINT fk_movimiento_orden FOREIGN KEY (orden_trabajo_id) REFERENCES orden_trabajo (id),
    ADD CONSTRAINT fk_movimiento_linea FOREIGN KEY (linea_ot_id)      REFERENCES linea_ot (id),
    -- Una salida de almacen siempre se justifica: o va contra una OT o lleva motivo.
    ADD CONSTRAINT ck_movimiento_salida_justificada CHECK (
        tipo <> 'SALIDA' OR orden_trabajo_id IS NOT NULL OR motivo IS NOT NULL
    );
