-- =====================================================================
-- V5 - Facturacion: series, facturas, lineas, desglose de IVA y eventos
-- =====================================================================
-- Principios que sostiene este esquema:
--   1. Una factura emitida es INMUTABLE: no se edita ni se borra jamas.
--      Las correcciones se hacen con una factura rectificativa que
--      referencia a la original.
--   2. La numeracion es correlativa y SIN HUECOS por serie y ejercicio,
--      garantizado a nivel de base de datos (contador transaccional +
--      trigger de validacion en V6).
--   3. Los datos fiscales de emisor y receptor y las lineas se COPIAN
--      (no se referencian) en el momento de la emision.
--   4. Cada factura encadena su huella con la de la anterior, formando una
--      cadena verificable de extremo a extremo.
-- =====================================================================


-- ---------------------------------------------------------------------
-- Series de facturacion
-- ---------------------------------------------------------------------
CREATE TABLE serie_factura (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(10)  NOT NULL,
    ejercicio     INTEGER      NOT NULL,
    descripcion   VARCHAR(150) NOT NULL,
    tipo          VARCHAR(20)  NOT NULL DEFAULT 'ORDINARIA',
    -- Contador transaccional. Se incrementa con la fila bloqueada
    -- (SELECT ... FOR UPDATE) en la misma transaccion que inserta la factura,
    -- de modo que un rollback nunca deja un hueco en la numeracion.
    ultimo_numero INTEGER      NOT NULL DEFAULT 0,
    activa        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_by    BIGINT,
    version       INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT uq_serie_factura        UNIQUE (codigo, ejercicio),
    CONSTRAINT ck_serie_factura_tipo   CHECK (tipo IN ('ORDINARIA', 'RECTIFICATIVA')),
    CONSTRAINT ck_serie_factura_numero CHECK (ultimo_numero >= 0),
    CONSTRAINT ck_serie_factura_anio   CHECK (ejercicio BETWEEN 2000 AND 2200),
    CONSTRAINT fk_serie_factura_created_by FOREIGN KEY (created_by) REFERENCES usuario (id),
    CONSTRAINT fk_serie_factura_updated_by FOREIGN KEY (updated_by) REFERENCES usuario (id)
);

COMMENT ON TABLE  serie_factura               IS 'Series de facturacion por ejercicio. Las rectificativas usan serie propia.';
COMMENT ON COLUMN serie_factura.ultimo_numero IS 'Ultimo numero emitido. Contador transaccional: garantiza numeracion sin huecos.';


-- ---------------------------------------------------------------------
-- Contador global del registro de facturacion (cadena de huellas)
-- ---------------------------------------------------------------------
-- Todas las facturas, sea cual sea su serie, se encadenan en un unico
-- registro ordenado. numero_registro da ese orden total.
CREATE TABLE contador_registro_facturacion (
    id            INTEGER PRIMARY KEY DEFAULT 1,
    ultimo_numero BIGINT  NOT NULL DEFAULT 0,

    CONSTRAINT ck_contador_registro_fila_unica CHECK (id = 1),
    CONSTRAINT ck_contador_registro_numero     CHECK (ultimo_numero >= 0)
);

INSERT INTO contador_registro_facturacion (id, ultimo_numero) VALUES (1, 0);

COMMENT ON TABLE contador_registro_facturacion IS 'Contador global del registro de facturacion. Fila unica (id = 1).';


-- ---------------------------------------------------------------------
-- Facturas
-- ---------------------------------------------------------------------
CREATE TABLE factura (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ----- Identificacion -----
    serie_id            BIGINT       NOT NULL,
    -- Copia del codigo de serie y del ejercicio: la factura debe poder leerse
    -- integra sin depender de otras tablas.
    serie_codigo        VARCHAR(10)  NOT NULL,
    ejercicio           INTEGER      NOT NULL,
    numero              INTEGER      NOT NULL,
    numero_completo     VARCHAR(40)  GENERATED ALWAYS AS
                            (serie_codigo || '/' || ejercicio::text || '/' || LPAD(numero::text, 6, '0')) STORED,
    tipo                VARCHAR(20)  NOT NULL DEFAULT 'ORDINARIA',

    -- ----- Origen y rectificacion -----
    orden_trabajo_id     BIGINT,
    factura_rectificada_id BIGINT,
    tipo_rectificativa   VARCHAR(20),
    motivo_rectificacion TEXT,

    -- ----- Fechas -----
    fecha_emision       DATE         NOT NULL DEFAULT CURRENT_DATE,
    fecha_operacion     DATE         NOT NULL DEFAULT CURRENT_DATE,
    timestamp_emision   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    -- ----- Datos fiscales del EMISOR, congelados en la emision -----
    emisor_razon_social VARCHAR(200) NOT NULL,
    emisor_nif          VARCHAR(20)  NOT NULL,
    emisor_direccion    VARCHAR(200) NOT NULL,
    emisor_cp           VARCHAR(10)  NOT NULL,
    emisor_ciudad       VARCHAR(100) NOT NULL,
    emisor_provincia    VARCHAR(100) NOT NULL,
    emisor_pais         VARCHAR(60)  NOT NULL,

    -- ----- Datos fiscales del RECEPTOR, congelados en la emision -----
    receptor_id         BIGINT,
    receptor_nombre     VARCHAR(250) NOT NULL,
    receptor_nif        VARCHAR(20)  NOT NULL,
    receptor_direccion  VARCHAR(200) NOT NULL,
    receptor_cp         VARCHAR(10)  NOT NULL,
    receptor_ciudad     VARCHAR(100) NOT NULL,
    receptor_provincia  VARCHAR(100) NOT NULL,
    receptor_pais       VARCHAR(60)  NOT NULL,

    -- ----- Descripcion del servicio, congelada -----
    matricula           VARCHAR(15),
    descripcion_vehiculo VARCHAR(200),
    codigo_ot           VARCHAR(20),

    -- ----- Importes -----
    base_imponible      NUMERIC(12,2) NOT NULL,
    total_iva           NUMERIC(12,2) NOT NULL,
    total               NUMERIC(12,2) NOT NULL,

    -- ----- Cadena de huellas (se completa en la fase 4) -----
    numero_registro     BIGINT        NOT NULL,
    -- Huella de la factura anterior de la cadena. La primera factura usa el
    -- valor genesis (64 ceros). Es NOT NULL + UNIQUE, asi que la cadena no
    -- puede bifurcarse: cada huella se consume exactamente una vez.
    huella_anterior     VARCHAR(64)      NOT NULL,
    huella              VARCHAR(64)      NOT NULL,
    -- Cadena canonica exacta sobre la que se calculo la huella. Se guarda para
    -- poder reverificar el hash anos despues aunque cambie el codigo.
    cadena_huella       TEXT          NOT NULL,
    algoritmo_huella    VARCHAR(20)   NOT NULL DEFAULT 'SHA-256',
    qr_contenido        TEXT,

    -- ----- Software emisor -----
    software_nombre     VARCHAR(100)  NOT NULL,
    software_version    VARCHAR(30)   NOT NULL,
    software_nif        VARCHAR(20),

    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by          BIGINT,

    CONSTRAINT uq_factura_numero          UNIQUE (serie_id, numero),
    CONSTRAINT uq_factura_numero_registro UNIQUE (numero_registro),
    CONSTRAINT uq_factura_huella          UNIQUE (huella),
    -- Impide bifurcaciones de la cadena: dos facturas no pueden declarar la
    -- misma huella anterior.
    CONSTRAINT uq_factura_huella_anterior UNIQUE (huella_anterior),

    CONSTRAINT ck_factura_tipo   CHECK (tipo IN ('ORDINARIA', 'RECTIFICATIVA')),
    CONSTRAINT ck_factura_numero CHECK (numero > 0),
    -- Una rectificativa referencia obligatoriamente a la factura corregida y
    -- explica el motivo; una ordinaria no puede llevar esos campos.
    CONSTRAINT ck_factura_rectificativa CHECK (
        (tipo = 'RECTIFICATIVA' AND factura_rectificada_id IS NOT NULL
                                AND tipo_rectificativa IS NOT NULL
                                AND motivo_rectificacion IS NOT NULL) OR
        (tipo = 'ORDINARIA'     AND factura_rectificada_id IS NULL
                                AND tipo_rectificativa IS NULL
                                AND motivo_rectificacion IS NULL)
    ),
    CONSTRAINT ck_factura_tipo_rectificativa CHECK (
        tipo_rectificativa IS NULL OR tipo_rectificativa IN ('POR_SUSTITUCION', 'POR_DIFERENCIAS')
    ),
    -- Las ordinarias siempre nacen de una OT.
    CONSTRAINT ck_factura_origen  CHECK (tipo = 'RECTIFICATIVA' OR orden_trabajo_id IS NOT NULL),
    CONSTRAINT ck_factura_totales CHECK (total = base_imponible + total_iva),
    CONSTRAINT ck_factura_huellas CHECK (
        huella ~ '^[0-9a-f]{64}$' AND huella_anterior ~ '^[0-9a-f]{64}$' AND huella <> huella_anterior
    ),
    CONSTRAINT ck_factura_registro CHECK (numero_registro > 0),

    CONSTRAINT fk_factura_serie      FOREIGN KEY (serie_id)              REFERENCES serie_factura (id),
    CONSTRAINT fk_factura_orden      FOREIGN KEY (orden_trabajo_id)      REFERENCES orden_trabajo (id),
    CONSTRAINT fk_factura_rectifica  FOREIGN KEY (factura_rectificada_id) REFERENCES factura (id),
    CONSTRAINT fk_factura_receptor   FOREIGN KEY (receptor_id)           REFERENCES cliente (id),
    CONSTRAINT fk_factura_created_by FOREIGN KEY (created_by)            REFERENCES usuario (id)
);

CREATE UNIQUE INDEX ux_factura_numero_completo ON factura (numero_completo);

CREATE INDEX ix_factura_fecha     ON factura (fecha_emision DESC, id DESC);
CREATE INDEX ix_factura_receptor  ON factura (receptor_id, fecha_emision DESC);
CREATE INDEX ix_factura_orden     ON factura (orden_trabajo_id);
CREATE INDEX ix_factura_rectifica ON factura (factura_rectificada_id) WHERE factura_rectificada_id IS NOT NULL;

COMMENT ON TABLE  factura                 IS 'Factura emitida. INMUTABLE: los triggers de V6 rechazan UPDATE y DELETE.';
COMMENT ON COLUMN factura.numero_registro IS 'Posicion en el registro global de facturacion. Da el orden total de la cadena de huellas.';
COMMENT ON COLUMN factura.huella_anterior IS 'Huella de la factura previa. La primera usa el valor genesis (64 ceros).';
COMMENT ON COLUMN factura.cadena_huella   IS 'Texto canonico exacto que se paso por SHA-256. Permite reverificar la huella en el futuro.';
COMMENT ON COLUMN factura.receptor_id     IS 'Referencia informativa al cliente. Los datos fiscales que valen son los copiados.';


-- ---------------------------------------------------------------------
-- Lineas de factura
-- ---------------------------------------------------------------------
-- COPIADAS desde la OT, no referenciadas. No hay clave ajena a pieza ni a
-- linea_ot a proposito: la factura debe seguir siendo legible e integra
-- aunque el catalogo cambie por completo.
CREATE TABLE linea_factura (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id      BIGINT        NOT NULL,
    numero_linea    INTEGER       NOT NULL,
    tipo            VARCHAR(20)   NOT NULL,
    descripcion     VARCHAR(300)  NOT NULL,
    -- Copia textual del SKU. Sin clave ajena: es una instantanea historica.
    pieza_sku       VARCHAR(50),
    cantidad        NUMERIC(12,3) NOT NULL,
    precio_unitario NUMERIC(12,4) NOT NULL,
    descuento_pct   NUMERIC(5,2)  NOT NULL DEFAULT 0,
    tipo_iva        VARCHAR(20)   NOT NULL,
    porcentaje_iva  NUMERIC(5,2)  NOT NULL,

    base_imponible NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)) STORED,
    cuota_iva      NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,
    total          NUMERIC(12,2) GENERATED ALWAYS AS
        (ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2)
         + ROUND(ROUND(cantidad * precio_unitario * (1 - descuento_pct / 100), 2) * porcentaje_iva / 100, 2)) STORED,

    CONSTRAINT uq_linea_factura_numero UNIQUE (factura_id, numero_linea),
    CONSTRAINT ck_linea_factura_tipo      CHECK (tipo IN ('MANO_DE_OBRA', 'PIEZA')),
    CONSTRAINT ck_linea_factura_cantidad  CHECK (cantidad <> 0),
    CONSTRAINT ck_linea_factura_descuento CHECK (descuento_pct >= 0 AND descuento_pct <= 100),
    CONSTRAINT ck_linea_factura_iva       CHECK (porcentaje_iva >= 0 AND porcentaje_iva <= 100),
    CONSTRAINT fk_linea_factura FOREIGN KEY (factura_id) REFERENCES factura (id)
);

CREATE INDEX ix_linea_factura ON linea_factura (factura_id, numero_linea);

COMMENT ON TABLE  linea_factura           IS 'Lineas copiadas de la OT. Sin FK al catalogo: instantanea historica inmutable.';
COMMENT ON COLUMN linea_factura.cantidad  IS 'Puede ser negativa en rectificativas por diferencias.';


-- ---------------------------------------------------------------------
-- Desglose por tipo de IVA
-- ---------------------------------------------------------------------
CREATE TABLE desglose_iva_factura (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id     BIGINT        NOT NULL,
    tipo_iva       VARCHAR(20)   NOT NULL,
    porcentaje_iva NUMERIC(5,2)  NOT NULL,
    base_imponible NUMERIC(12,2) NOT NULL,
    cuota_iva      NUMERIC(12,2) NOT NULL,

    CONSTRAINT uq_desglose_iva     UNIQUE (factura_id, porcentaje_iva),
    CONSTRAINT ck_desglose_iva_pct CHECK (porcentaje_iva >= 0 AND porcentaje_iva <= 100),
    CONSTRAINT fk_desglose_factura FOREIGN KEY (factura_id) REFERENCES factura (id)
);

CREATE INDEX ix_desglose_factura ON desglose_iva_factura (factura_id);

COMMENT ON TABLE desglose_iva_factura IS 'Base y cuota agrupadas por tipo de IVA. Una fila por porcentaje presente en la factura.';


-- ---------------------------------------------------------------------
-- Registro de eventos de facturacion
-- ---------------------------------------------------------------------
-- Bitacora append-only de todo lo que le ocurre al subsistema de facturacion:
-- emisiones, rectificaciones, exportaciones, verificaciones e incidencias.
CREATE TABLE evento_factura (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id  BIGINT,
    tipo_evento VARCHAR(30)  NOT NULL,
    fecha       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    usuario_id  BIGINT,
    descripcion VARCHAR(500) NOT NULL,
    detalle     JSONB,
    ip_origen   VARCHAR(45),

    CONSTRAINT ck_evento_tipo CHECK (tipo_evento IN (
        'EMISION', 'RECTIFICACION', 'GENERACION_PDF', 'EXPORTACION',
        'VERIFICACION_CADENA', 'CONSULTA', 'INCIDENCIA')),
    CONSTRAINT fk_evento_factura FOREIGN KEY (factura_id) REFERENCES factura (id),
    CONSTRAINT fk_evento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_evento_factura ON evento_factura (factura_id, fecha DESC);
CREATE INDEX ix_evento_tipo    ON evento_factura (tipo_evento, fecha DESC);

COMMENT ON TABLE evento_factura IS 'Bitacora append-only del subsistema de facturacion. No se edita ni se borra.';
